### PR TITLE
Incoming documents / OTA update ESP8266 example / Markdown for outgoing messages / Fix ESP reboot using command

### PR DESCRIPTION
**Pull request by vlw**

### CODE REVIEW

**Comment by vlw** [comment]
@cotestatnt Hi. You can check how works OTA update here: https://github.com/vlw/AsyncTelegram/blob/master/examples/OTAupdate_ESP8266/README.md

**Comment by cotestatnt** [comment]
So many thanks Vladimir!
I've just merged your pull request.

**Comment by vlw** [comment]
@cotestatnt Thank you!
I guess it's good time to release new version.

**Comment by cotestatnt** [comment]
I will do soon.
Now i'm testing some speed improvements for file uploading and even try to manage a bug with HttpClient...Have you ever experienced memory leaks on connection errors? According to some issues opened on arduino-esp32 repo, it seems related to ssl handshake.
For the moment i've implemented only a work-around: when memory is not enough, task will be deleted and then restarted again.

memoryLeak

**Pull request merged**
